projects:
  cljstemplate:
    schemaPath: src/amplify/graphql/schema.json
    includes:
      - src/amplify/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/amplify/graphql
extensions:
  amplify:
    version: 3
